# Site settings
title: Guillermo Guerini
description: I'm a web & mobile developer, traveler, runner and sometimes, a triathlete.

email: a-mail@mail.mail
logo: "/assets/images/gui-logo.png"

name: Guillermo Guerini
author: Guillermo Guerini
author_image: "/assets/images/author.jpg"

paginate:	5

permalink: /:year/:month/:title

url: "https://gguerini.com"
baseurl: ""
google_analytics: "UA-1545602-5"

# social icons and sharing options
social:
  - icon:	twitter
    url: https://twitter.com/gguerini
    desc: Follow me on twitter
    share_url: https://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/gguerini
    desc:	Fork me on github

# Build settings
markdown: kramdown

# Gems
gems:
  - jekyll-paginate
  - jekyll-sitemap
