# Site settings
title: Guillermo Guerini
description: I'm a software engineer specialized in Web and Mobile development with 10+ years of experience.

email: a-mail@mail.mail
logo: "/assets/images/gui-logo.png"
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: Guillermo Guerini
author: Guillermo Guerini
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://gguerini.com"
baseurl: ""
google_analytics: "UA-1545602-5"

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/gguerini
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

#  - icon:	github
#    url:	https://github.com/dirkfabisch
#    desc:	Fork me on github
#    share_url:
#    share_title:
#    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:

# Build settings
markdown: kramdown

# Gems
gems: [jekyll-paginate]
